# Rustfmt configuration for Cem
# Ensures formatting matches clippy's expectations

edition = "2024"

# Import ordering - match clippy's expectations
# imports_granularity = "Crate"
# group_imports = "StdExternalCrate"

# Consistent formatting
max_width = 100
use_small_heuristics = "Default"
