[package]
name = "cem"
version = "0.1.0"
edition = "2024"

[dependencies]
# No external dependencies! We generate LLVM IR as text and call clang directly.
# This works with any LLVM version (10, 15, 18, 19, 21+)
# See docs/LLVM_TEXT_IR.md for rationale.
