# Cargo configuration for Cem compiler
#
# LLVM Configuration:
# Set the LLVM_SYS_180_PREFIX environment variable to your LLVM 18 installation.
#
# Examples:
#   macOS (Homebrew): export LLVM_SYS_180_PREFIX=/opt/homebrew/opt/llvm@18
#   Linux (Ubuntu):   export LLVM_SYS_180_PREFIX=/usr/lib/llvm-18
#   Custom install:   export LLVM_SYS_180_PREFIX=/path/to/llvm-18
#
# See BUILD.md for detailed setup instructions.

[build]
# Additional rustc flags can go here if needed
# rustflags = []
