# Cargo configuration for Cem compiler
# This sets up environment variables needed for LLVM compilation

[env]
# LLVM 18 installation path
LLVM_SYS_180_PREFIX = "/opt/homebrew/opt/llvm@18"

# Library search path for linking (includes zstd and other deps)
LIBRARY_PATH = "/opt/homebrew/lib"

[build]
# Additional rustc flags can go here if needed
# rustflags = []

[target.aarch64-apple-darwin]
# macOS ARM64 specific configuration
rustflags = [
    "-C", "link-arg=-L/opt/homebrew/lib",
]

[target.x86_64-apple-darwin]
# macOS x86_64 specific configuration
rustflags = [
    "-C", "link-arg=-L/opt/homebrew/lib",
]
